# Generated by Django 4.0.2 on 2022-02-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mokininys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vardas', models.CharField(max_length=30)),
                ('pavarde', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('telefono_numeris', models.CharField(max_length=12)),
            ],
        ),
    ]
