# Generated by Django 4.0.2 on 2022-02-20 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pradziamokslis', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mokininys',
            new_name='Mokinys',
        ),
        migrations.AlterModelOptions(
            name='mokinys',
            options={'verbose_name_plural': 'Mokiniai'},
        ),
    ]
